name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate changelog
      id: changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      with:
        onlyLastTag: "true"
        stripHeaders: "true"
        stripGeneratorNotice: "true"
    - name: Upload changelog
      uses: actions/upload-artifact@v2
      with:
        name: changelog
        path: CHANGELOG.md
    - name: Create release
      uses: actions/create-release@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog.outputs.changelog }}
        prerelease: false
  plugin:
    name: Publish plugin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Log in to Gradle plugin portal
      run: |
        mkdir -p ~/.gradle
        touch ~/.gradle/gradle.properties
        echo gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} >> ~/.gradle/gradle.properties
        echo gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} >> ~/.gradle/gradle.properties
    - name: Publish release artifacts
      run: >-
        ./gradlew
        -Psnapshot=false
        -PgithubUser=${{ github.actor }}
        -PgithubPass=${{ secrets.GITHUB_TOKEN }}
        -Dgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
        -Dgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
        publishAllPublicationsToGithubRepository publishPlugins
